#ifndef __GPIO_H__
#define __GPIO_H__

#include <stdint.h>

// The main pointer type we use
typedef volatile uint32_t * ptr_t;

/*
 * Write the gpio_moder register given such as pin is an input.
 */
void set_as_input(ptr_t gpio_moder, int pin);

/*
 * Write the gpio_moder register given such as pin is an output.
 */
void set_as_output(ptr_t gpio_moder, int pin);

#define ADDR_ADD_OFFSET(addr, offet) (*(ptr_t)((addr) + (offet)))

// sets the bit of the given variable
#define set_bit(addr, bit) (addr) |= 1 << (bit)
// unsets the bit of the given variable
#define unset_bit(addr, bit) (addr) &= ~(1 << (bit))

// adds the bit in the given integer
#define add_bit(val, bit) ((val) | (1 << (bit)))
// removes the bit in the given integer
#define del_bit(val, bit) ((val) & (~(1 << (bit))))

// RCC register
#define RCC_ADDR 0x40021000

// AHB2 clock enable register
#define RCC_AHB2ENR ADDR_ADD_OFFSET(RCC_ADDR, 0x4C)

// for each gpio, the corresponding bit in RCC_AHB2 (to enable the clock)
#define RCC_AHB2ENR_A 0
#define RCC_AHB2ENR_B 1
#define RCC_AHB2ENR_C 2
#define RCC_AHB2ENR_D 3
#define RCC_AHB2ENR_E 4
#define RCC_AHB2ENR_F 5
#define RCC_AHB2ENR_G 6
#define RCC_AHB2ENR_H 7
#define RCC_AHB2ENR_I 8

// GPIO registers
#define GPIOA_ADDR 0x48000000
#define GPIOB_ADDR 0x48000400
#define GPIOC_ADDR 0x48000800
#define GPIOD_ADDR 0x48000C00
#define GPIOE_ADDR 0x48001000
#define GPIOF_ADDR 0x48001400
#define GPIOG_ADDR 0x48001800
#define GPIOH_ADDR 0x48001C00
#define GPIOI_ADDR 0x48002000

// GPIO MODER
#define OFFSET_GPIO_MODER 0x00
#define GPIOA_MODER ADDR_ADD_OFFSET(GPIOA_ADDR, OFFSET_GPIO_MODER)
#define GPIOB_MODER ADDR_ADD_OFFSET(GPIOB_ADDR, OFFSET_GPIO_MODER)
#define GPIOC_MODER ADDR_ADD_OFFSET(GPIOC_ADDR, OFFSET_GPIO_MODER)
#define GPIOD_MODER ADDR_ADD_OFFSET(GPIOD_ADDR, OFFSET_GPIO_MODER)
#define GPIOE_MODER ADDR_ADD_OFFSET(GPIOE_ADDR, OFFSET_GPIO_MODER)
#define GPIOF_MODER ADDR_ADD_OFFSET(GPIOF_ADDR, OFFSET_GPIO_MODER)
#define GPIOG_MODER ADDR_ADD_OFFSET(GPIOG_ADDR, OFFSET_GPIO_MODER)
#define GPIOH_MODER ADDR_ADD_OFFSET(GPIOH_ADDR, OFFSET_GPIO_MODER)
#define GPIOI_MODER ADDR_ADD_OFFSET(GPIOI_ADDR, OFFSET_GPIO_MODER)

// GPIO OTYPER
#define OFFSET_GPIO_OTYPER 0x04
#define GPIOA_OTYPER ADDR_ADD_OFFSET(GPIOA_ADDR, OFFSET_GPIO_OTYPER)
#define GPIOB_OTYPER ADDR_ADD_OFFSET(GPIOB_ADDR, OFFSET_GPIO_OTYPER)
#define GPIOC_OTYPER ADDR_ADD_OFFSET(GPIOC_ADDR, OFFSET_GPIO_OTYPER)
#define GPIOD_OTYPER ADDR_ADD_OFFSET(GPIOD_ADDR, OFFSET_GPIO_OTYPER)
#define GPIOE_OTYPER ADDR_ADD_OFFSET(GPIOE_ADDR, OFFSET_GPIO_OTYPER)
#define GPIOF_OTYPER ADDR_ADD_OFFSET(GPIOF_ADDR, OFFSET_GPIO_OTYPER)
#define GPIOG_OTYPER ADDR_ADD_OFFSET(GPIOG_ADDR, OFFSET_GPIO_OTYPER)
#define GPIOH_OTYPER ADDR_ADD_OFFSET(GPIOH_ADDR, OFFSET_GPIO_OTYPER)
#define GPIOI_OTYPER ADDR_ADD_OFFSET(GPIOI_ADDR, OFFSET_GPIO_OTYPER)

// GPIO OSPEEDR
#define OFFSET_GPIO_OSPEEDR 0x08
#define GPIOA_OSPEEDR ADDR_ADD_OFFSET(GPIOA_ADDR, OFFSET_GPIO_OSPEEDR)
#define GPIOB_OSPEEDR ADDR_ADD_OFFSET(GPIOB_ADDR, OFFSET_GPIO_OSPEEDR)
#define GPIOC_OSPEEDR ADDR_ADD_OFFSET(GPIOC_ADDR, OFFSET_GPIO_OSPEEDR)
#define GPIOD_OSPEEDR ADDR_ADD_OFFSET(GPIOD_ADDR, OFFSET_GPIO_OSPEEDR)
#define GPIOE_OSPEEDR ADDR_ADD_OFFSET(GPIOE_ADDR, OFFSET_GPIO_OSPEEDR)
#define GPIOF_OSPEEDR ADDR_ADD_OFFSET(GPIOF_ADDR, OFFSET_GPIO_OSPEEDR)
#define GPIOG_OSPEEDR ADDR_ADD_OFFSET(GPIOG_ADDR, OFFSET_GPIO_OSPEEDR)
#define GPIOH_OSPEEDR ADDR_ADD_OFFSET(GPIOH_ADDR, OFFSET_GPIO_OSPEEDR)
#define GPIOI_OSPEEDR ADDR_ADD_OFFSET(GPIOI_ADDR, OFFSET_GPIO_OSPEEDR)

// GPIO PUPDR
#define OFFSET_GPIO_PUPDR 0x0C
#define GPIOA_PUPDR ADDR_ADD_OFFSET(GPIOA_ADDR, OFFSET_GPIO_PUPDR)
#define GPIOB_PUPDR ADDR_ADD_OFFSET(GPIOB_ADDR, OFFSET_GPIO_PUPDR)
#define GPIOC_PUPDR ADDR_ADD_OFFSET(GPIOC_ADDR, OFFSET_GPIO_PUPDR)
#define GPIOD_PUPDR ADDR_ADD_OFFSET(GPIOD_ADDR, OFFSET_GPIO_PUPDR)
#define GPIOE_PUPDR ADDR_ADD_OFFSET(GPIOE_ADDR, OFFSET_GPIO_PUPDR)
#define GPIOF_PUPDR ADDR_ADD_OFFSET(GPIOF_ADDR, OFFSET_GPIO_PUPDR)
#define GPIOG_PUPDR ADDR_ADD_OFFSET(GPIOG_ADDR, OFFSET_GPIO_PUPDR)
#define GPIOH_PUPDR ADDR_ADD_OFFSET(GPIOH_ADDR, OFFSET_GPIO_PUPDR)
#define GPIOI_PUPDR ADDR_ADD_OFFSET(GPIOI_ADDR, OFFSET_GPIO_PUPDR)

// GPIO IDR
#define OFFSET_GPIO_IDR 0x10
#define GPIOA_IDR ADDR_ADD_OFFSET(GPIOA_ADDR, OFFSET_GPIO_IDR)
#define GPIOB_IDR ADDR_ADD_OFFSET(GPIOB_ADDR, OFFSET_GPIO_IDR)
#define GPIOC_IDR ADDR_ADD_OFFSET(GPIOC_ADDR, OFFSET_GPIO_IDR)
#define GPIOD_IDR ADDR_ADD_OFFSET(GPIOD_ADDR, OFFSET_GPIO_IDR)
#define GPIOE_IDR ADDR_ADD_OFFSET(GPIOE_ADDR, OFFSET_GPIO_IDR)
#define GPIOF_IDR ADDR_ADD_OFFSET(GPIOF_ADDR, OFFSET_GPIO_IDR)
#define GPIOG_IDR ADDR_ADD_OFFSET(GPIOG_ADDR, OFFSET_GPIO_IDR)
#define GPIOH_IDR ADDR_ADD_OFFSET(GPIOH_ADDR, OFFSET_GPIO_IDR)
#define GPIOI_IDR ADDR_ADD_OFFSET(GPIOI_ADDR, OFFSET_GPIO_IDR)

// GPIO ODR
#define OFFSET_GPIO_ODR 0x14
#define GPIOA_ODR ADDR_ADD_OFFSET(GPIOA_ADDR, OFFSET_GPIO_ODR)
#define GPIOB_ODR ADDR_ADD_OFFSET(GPIOB_ADDR, OFFSET_GPIO_ODR)
#define GPIOC_ODR ADDR_ADD_OFFSET(GPIOC_ADDR, OFFSET_GPIO_ODR)
#define GPIOD_ODR ADDR_ADD_OFFSET(GPIOD_ADDR, OFFSET_GPIO_ODR)
#define GPIOE_ODR ADDR_ADD_OFFSET(GPIOE_ADDR, OFFSET_GPIO_ODR)
#define GPIOF_ODR ADDR_ADD_OFFSET(GPIOF_ADDR, OFFSET_GPIO_ODR)
#define GPIOG_ODR ADDR_ADD_OFFSET(GPIOG_ADDR, OFFSET_GPIO_ODR)
#define GPIOH_ODR ADDR_ADD_OFFSET(GPIOH_ADDR, OFFSET_GPIO_ODR)
#define GPIOI_ODR ADDR_ADD_OFFSET(GPIOI_ADDR, OFFSET_GPIO_ODR)

// GPIO BSRR
#define OFFSET_GPIO_BSRR 0x18
#define GPIOA_BSRR ADDR_ADD_OFFSET(GPIOA_ADDR, OFFSET_GPIO_BSRR)
#define GPIOB_BSRR ADDR_ADD_OFFSET(GPIOB_ADDR, OFFSET_GPIO_BSRR)
#define GPIOC_BSRR ADDR_ADD_OFFSET(GPIOC_ADDR, OFFSET_GPIO_BSRR)
#define GPIOD_BSRR ADDR_ADD_OFFSET(GPIOD_ADDR, OFFSET_GPIO_BSRR)
#define GPIOE_BSRR ADDR_ADD_OFFSET(GPIOE_ADDR, OFFSET_GPIO_BSRR)
#define GPIOF_BSRR ADDR_ADD_OFFSET(GPIOF_ADDR, OFFSET_GPIO_BSRR)
#define GPIOG_BSRR ADDR_ADD_OFFSET(GPIOG_ADDR, OFFSET_GPIO_BSRR)
#define GPIOH_BSRR ADDR_ADD_OFFSET(GPIOH_ADDR, OFFSET_GPIO_BSRR)
#define GPIOI_BSRR ADDR_ADD_OFFSET(GPIOI_ADDR, OFFSET_GPIO_BSRR)

// GPIO LCKR
#define OFFSET_GPIO_LCKR 0x1C
#define GPIOA_LCKR ADDR_ADD_OFFSET(GPIOA_ADDR, OFFSET_GPIO_LCKR)
#define GPIOB_LCKR ADDR_ADD_OFFSET(GPIOB_ADDR, OFFSET_GPIO_LCKR)
#define GPIOC_LCKR ADDR_ADD_OFFSET(GPIOC_ADDR, OFFSET_GPIO_LCKR)
#define GPIOD_LCKR ADDR_ADD_OFFSET(GPIOD_ADDR, OFFSET_GPIO_LCKR)
#define GPIOE_LCKR ADDR_ADD_OFFSET(GPIOE_ADDR, OFFSET_GPIO_LCKR)
#define GPIOF_LCKR ADDR_ADD_OFFSET(GPIOF_ADDR, OFFSET_GPIO_LCKR)
#define GPIOG_LCKR ADDR_ADD_OFFSET(GPIOG_ADDR, OFFSET_GPIO_LCKR)
#define GPIOH_LCKR ADDR_ADD_OFFSET(GPIOH_ADDR, OFFSET_GPIO_LCKR)
#define GPIOI_LCKR ADDR_ADD_OFFSET(GPIOI_ADDR, OFFSET_GPIO_LCKR)

// GPIO AFRL
#define OFFSET_GPIO_AFRL 0x20
#define GPIOA_AFRL ADDR_ADD_OFFSET(GPIOA_ADDR, OFFSET_GPIO_AFRL)
#define GPIOB_AFRL ADDR_ADD_OFFSET(GPIOB_ADDR, OFFSET_GPIO_AFRL)
#define GPIOC_AFRL ADDR_ADD_OFFSET(GPIOC_ADDR, OFFSET_GPIO_AFRL)
#define GPIOD_AFRL ADDR_ADD_OFFSET(GPIOD_ADDR, OFFSET_GPIO_AFRL)
#define GPIOE_AFRL ADDR_ADD_OFFSET(GPIOE_ADDR, OFFSET_GPIO_AFRL)
#define GPIOF_AFRL ADDR_ADD_OFFSET(GPIOF_ADDR, OFFSET_GPIO_AFRL)
#define GPIOG_AFRL ADDR_ADD_OFFSET(GPIOG_ADDR, OFFSET_GPIO_AFRL)
#define GPIOH_AFRL ADDR_ADD_OFFSET(GPIOH_ADDR, OFFSET_GPIO_AFRL)
#define GPIOI_AFRL ADDR_ADD_OFFSET(GPIOI_ADDR, OFFSET_GPIO_AFRL)

// GPIO AFRH
#define OFFSET_GPIO_AFRH 0x24
#define GPIOA_AFRH ADDR_ADD_OFFSET(GPIOA_ADDR, OFFSET_GPIO_AFRH)
#define GPIOB_AFRH ADDR_ADD_OFFSET(GPIOB_ADDR, OFFSET_GPIO_AFRH)
#define GPIOC_AFRH ADDR_ADD_OFFSET(GPIOC_ADDR, OFFSET_GPIO_AFRH)
#define GPIOD_AFRH ADDR_ADD_OFFSET(GPIOD_ADDR, OFFSET_GPIO_AFRH)
#define GPIOE_AFRH ADDR_ADD_OFFSET(GPIOE_ADDR, OFFSET_GPIO_AFRH)
#define GPIOF_AFRH ADDR_ADD_OFFSET(GPIOF_ADDR, OFFSET_GPIO_AFRH)
#define GPIOG_AFRH ADDR_ADD_OFFSET(GPIOG_ADDR, OFFSET_GPIO_AFRH)
#define GPIOH_AFRH ADDR_ADD_OFFSET(GPIOH_ADDR, OFFSET_GPIO_AFRH)
#define GPIOI_AFRH ADDR_ADD_OFFSET(GPIOI_ADDR, OFFSET_GPIO_AFRH)

// GPIO BRR
#define OFFSET_GPIO_BRR 0x28
#define GPIOA_BRR ADDR_ADD_OFFSET(GPIOA_ADDR, OFFSET_GPIO_BRR)
#define GPIOB_BRR ADDR_ADD_OFFSET(GPIOB_ADDR, OFFSET_GPIO_BRR)
#define GPIOC_BRR ADDR_ADD_OFFSET(GPIOC_ADDR, OFFSET_GPIO_BRR)
#define GPIOD_BRR ADDR_ADD_OFFSET(GPIOD_ADDR, OFFSET_GPIO_BRR)
#define GPIOE_BRR ADDR_ADD_OFFSET(GPIOE_ADDR, OFFSET_GPIO_BRR)
#define GPIOF_BRR ADDR_ADD_OFFSET(GPIOF_ADDR, OFFSET_GPIO_BRR)
#define GPIOG_BRR ADDR_ADD_OFFSET(GPIOG_ADDR, OFFSET_GPIO_BRR)
#define GPIOH_BRR ADDR_ADD_OFFSET(GPIOH_ADDR, OFFSET_GPIO_BRR)
#define GPIOI_BRR ADDR_ADD_OFFSET(GPIOI_ADDR, OFFSET_GPIO_BRR)

// GPIO ASCR
#define OFFSET_GPIO_ASCR 0x2C
#define GPIOA_ASCR ADDR_ADD_OFFSET(GPIOA_ADDR, OFFSET_GPIO_ASCR)
#define GPIOB_ASCR ADDR_ADD_OFFSET(GPIOB_ADDR, OFFSET_GPIO_ASCR)
#define GPIOC_ASCR ADDR_ADD_OFFSET(GPIOC_ADDR, OFFSET_GPIO_ASCR)
#define GPIOD_ASCR ADDR_ADD_OFFSET(GPIOD_ADDR, OFFSET_GPIO_ASCR)
#define GPIOE_ASCR ADDR_ADD_OFFSET(GPIOE_ADDR, OFFSET_GPIO_ASCR)
#define GPIOF_ASCR ADDR_ADD_OFFSET(GPIOF_ADDR, OFFSET_GPIO_ASCR)
#define GPIOG_ASCR ADDR_ADD_OFFSET(GPIOG_ADDR, OFFSET_GPIO_ASCR)
#define GPIOH_ASCR ADDR_ADD_OFFSET(GPIOH_ADDR, OFFSET_GPIO_ASCR)
#define GPIOI_ASCR ADDR_ADD_OFFSET(GPIOI_ADDR, OFFSET_GPIO_ASCR)

// pins
#define P00 0x0
#define P01 0x1
#define P02 0x2
#define P03 0x3
#define P04 0x4
#define P05 0x5
#define P06 0x6
#define P07 0x7
#define P08 0x8
#define P09 0x9
#define P10 0xa
#define P11 0xb
#define P12 0xc
#define P13 0xd
#define P14 0xe
#define P15 0xf

#endif
